### ISSUE TITLE
4 Speed Bypasses On LiquidBounce

### ISSUE THREAD

**Issue by coolpvpv1** [tombola46/NegativityAddon#10]
Describe the bug/bypass
if you go on liquidbounce look at speeds and choose either ncphop, aac3bhop, hivehop, or mineplexground those 4 speed works and make sure the mineplexground-speed is 0.5 or lower to work for me mineplexground is the fastest

Negativity Addon and Negativity version
1.3 and 1.4.1

Logs/Proof
it's a bypass so it doesn't show any logs

Screenshots/video
not needed and obs can't record anyway

Additional context
This was done on spigot 1.8.8

**Comment by tombola46** [comment]
Thanks for reporting a lot !

I will try to fix this in next version :)

**Comment by tombola46** [comment]
HiveHop, AAC3BHop fixed in Addon.
Other will be fixed soon in Negativity or Addon
