### ISSUE TITLE
Speed False Flag Maybe?

### ISSUE THREAD

**Issue by coolpvpv1** [tombola46/NegativityAddon#11]
Describe the bug/bypass
i tried sleeping in a bed and my screen gets setback sometimes so i thought it might be falsing speed or something idk cause it doesn't happen normally

Negativity Addon and Negativity version
1.3 and 1.4.1

Logs/Proof
doesn't show any logs

Screenshots/video
obs doesn't want to record my screen idk why

Additional context
this was done on spigot 1.8.8

**Comment by tombola46** [comment]
Thanks for reporting !

I will test it ! And if there is any false flag it will be fixed  :)
