### ISSUE TITLE
Speed False Flag (two)

### ISSUE THREAD

**Issue by coolpvpv1** [tombola46/NegativityAddon#14]
Describe the bug/bypass
on spigot 1.15.2 if you place a honey block on the ground go on it then jump when you hit the honey block back on the ground you will false speed and if you tower up and try to go down on the sides of the honey blocks you towered up with you will also false speed

Negativity Addon and Negativity version
1.3 and 1.4.1

Logs/Proof

Screenshots/video
not needed

Additional context
this was done on spigot 1.15.2

**Comment by tombola46** [comment]
Thanks for reporting !

As I said NegativityAddon is mainly for 1.8 so I will firstly fix bugs with 1.8 and then others.
But anyways thanks for reporting.

**Comment by coolpvpv1** [comment]
> Thanks for reporting !
> 
> As I said NegativityAddon is mainly for 1.8 so I will firstly fix bugs with 1.8 and then others.
> But anyways thanks for reporting.

ik even if it's just for 1.8 i just report them anyway to see if they will get fixed or not

**Comment by tombola46** [comment]
I am going to support only 1.8... sorry
