### ISSUE TITLE
Console Error On 1.7.10

### ISSUE THREAD

**Issue by coolpvpv1** [tombola46/NegativityAddon#15]
Describe the bug/bypass
if you use negativity and negativityaddon on 1.7.10 it will shot a error in console for negativity addon here is it https://paste.ubuntu.com/p/Yh4k9znm7k/

Negativity Addon and Negativity version
1.3 and 1.4.1

**Comment by coolpvpv1** [comment]
heres this one two if you move on 1.7.10 it gives you this error https://paste.ubuntu.com/p/56WQbXT3fB/

**Comment by tombola46** [comment]
Thanks for reporting !

This bug is maybe because NegativityAddon is not made for 1.7.10 at all.
But I will look at this :)

**Comment by tombola46** [comment]
I am not going to support 1.7.10
