### ISSUE TITLE
Speed False Flags With Knockback

### ISSUE THREAD

**Issue by coolpvpv1** [tombola46/NegativityAddon#16]
**Describe the bug/bypass**
im tired at 1 am so im only filling these two slots if you get knocked back by a skeleton zombie creeper or whatever it will false speed

**Negativity Addon and Negativity version**
1.3 and 1.4.1

**Comment by tombola46** [comment]
Thanks for reporting !

I will try to fix this issue :)
But sadly I am not here from 27.1.2020 to 31.1.2020 so please be patient.

**Comment by tombola46** [comment]
Fixed
