### ISSUE TITLE
Speed Falses And RubberBand Glitch

### ISSUE THREAD

**Issue by coolpvpv1** [tombola46/NegativityAddon#2]
Describe the bug/bypass
if you speed onground really fast it will glitch you forward and back alot infinitly until you relog and if you have jump boost 2 effect sprint and jump you will false speed if you have blocks above your head in a huge line and you sprint and jump under the blocks above your head you will false speed 

Negativity Addon and Negativity version
1.1 and 1.4.1

Logs/Proof
https://paste.ubuntu.com/p/8F95nRWG6Z/

Screenshots/video
obs has mental aids so i cant record

Additional context
this was done on spigot 1.8.8 https://getbukkit.org/get/hNiHm0tuqAg1Xg7w7zudk63uHr0xo48D

**Comment by tombola46** [comment]
Thanks for reporting a lot !
These bugs will be fixed in new version 1.3 !

Stay tuned :)

**Comment by tombola46** [comment]
Fixed in new version (1.2) :)
