### ISSUE TITLE
Speed Falses Again Yay

### ISSUE THREAD

**Issue by coolpvpv1** [tombola46/NegativityAddon#3]
Describe the bug/bypass
jump boost 2 sprinting and jumping still falses speed and another false with trapdoors if you put the trapdoors on the roof or the floor either way when you sprint and jump you false speed https://i.badlion.net/DfKs7updV4o6CvF3jZ7A7F.png

Negativity Addon and Negativity version
1.2 and 1.4.1

Logs/Proof
isn't showing any logs idk why

Screenshots/video
obs stupid so i cant

Additional context
it still falses yay

**Comment by tombola46** [comment]
Thanks for reporting a lot :)
I will try to fix these bugs in next version !

Stay tuned !

**Comment by coolpvpv1** [comment]
> Thanks for reporting a lot :)
> I will try to fix these bugs in next version !
> 
> Stay tuned !

https://www.spigotmc.org/wiki/anti-cheat-list-bukkit-and-spigot-1-8-x/ look next to the negativity anticheat lol

**Comment by tombola46** [comment]
lool :D

**Comment by coolpvpv1** [comment]
> lool :D

i added that so i guess more people will see it
